In [1]:
import numpy as np
l1 = [1, 2, 3]

l2 = [[1, 2, 3],
     [11, 22, 33]]

l3 = [[[1, 2, 3]]]

In [3]:
array1 = np.array(l1)

print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)  # 튜플의 법칙때문에~ (3,)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [4]:
array2 = np.array(l2)

print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [5]:
array3 = np.array(l3)

print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 1, 3)


In [7]:
### 각 array의 차원을 살펴보면,

print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 3차원


# array의 데이터 자료 확인

In [10]:
list1 = [1, 2, 'test']
array2 = np.array(list1)
print(array2, array2.dtype)

list2 = [1, 2, 3.4]
array3 = np.array(list2)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1.  2.  3.4] float64


# 각 자료들의 float 및 int 변환

In [11]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [16]:
array_int = np.array([1, 2, 3])
# 위의 array_int의 자료를 float으로 변환
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# array_float -> array_int1 데이터 변환
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

# 과연 실수데이트를 int로 변환시킬때 소수점 뒤의 자리는?
array_float1 = np.array([1.1 , 2.3, 4.4])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 4] int32


## ndarray를 편리하게 생성 - arange, zeros, ones

In [19]:
sq_array = np.arange(10)
print(sq_array)
print(sq_array.dtype, sq_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [20]:
sq_array = np.arange(4, 10)
print(sq_array)
print(sq_array.dtype, sq_array.shape)

[4 5 6 7 8 9]
int32 (6,)


In [23]:
print(np.zeros((3, 2), dtype='int32'))
print()
print(np.zeros((3, 2), dtype='float32'))
print()
print(np.zeros((3, 2), dtype='float64'))

[[0 0]
 [0 0]
 [0 0]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [24]:
zero_array = np.zeros((3, 2), dtype='float64')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2)


In [25]:
one_array = np.ones((3, 2), dtype = 'int32')
print(one_array)
print(one_array.dtype, one_array.shape)

[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2)


In [32]:
import pandas as pd
pd.read_csv('chipotle.csv')
pd.read_csv('C:/Users/user/Desktop/Statistic/study/titanic/train.csv')  # 절대경로
pd.read_csv('./train.csv') # 상대경로
# pd.read_csv('./test/train.csv') # 상대경로

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
# df = pd.read_csv(DataUrl, encoding='utf-8')
# df

# 만약 df으로 변환시
# df의 자료가 한글이 포함되어 안되는 경우
# encoding = 'utf-8' 혹은 'cp949' 혹은 'euc-kr'
# 중에서 골라서 적용한 후 사용하시면
# 확실하게 데이터를 로딩시키실 수 있습니다.

In [27]:
pd.read_csv('gender_submission.csv')

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [33]:
pd.read_csv('jeju.csv')
# pd.read_csv('jeju.csv', encoding='cp949')

Unnamed: 0     id          일자   시도명  읍면동명         거주인구       근무인구  \
0              0  22448  2018-01-01   제주시   도두동    32249.987   3418.266   
1              1  22449  2018-01-01   제주시   외도동   213500.997  10341.172   
2              2  22450  2018-01-01   제주시  이도2동  1212382.218  96920.834   
3              3  22451  2018-01-01   제주시  일도1동    33991.653   6034.253   
4              4  22452  2018-01-01  서귀포시   대천동   155036.925   9403.969   
...          ...    ...         ...   ...   ...          ...        ...   
9616        9616  32064  2020-04-30  서귀포시   표선면   228260.005  16891.732   
9617        9617  32065  2020-04-30   제주시   한림읍   459959.064  26007.122   
9618        9618  32066  2020-04-30   제주시   도두동    28397.481   3144.895   
9619        9619  32067  2020-04-30  서귀포시   안덕면   348037.846  29106.286   
9620        9620  32068  2020-04-30   제주시    연동  1010643.372  65673.477   

            방문인구       총 유동인구   평균 속도  평균 소요 시간  평균 기온  일강수량  평균 풍속  
0     102709.092   138377.345  39.556    29.167    5.0   0.0   2.50  
1     112692.789   336534.958  32.900    30.900    5.0   0.0   2.50  
2     541194.481  1850497.533  29.538    35.692    2.9   0.0   2.40  
3      72155.919   112181.825  30.000    23.500    2.9   0.0   2.40  
4     150882.409   315323.303  41.583    14.375    5.1   0.0   2.30  
...          ...          ...     ...       ...    ...   ...    ...  
9616  152832.449   397984.186  44.514    34.054   18.1   0.0   4.70  
9617  249700.419   735666.605  48.609    61.377   18.0   0.0   4.35  
9618   84052.697   115595.073  41.053    29.421   20.3   0.0   3.00  
9619  251129.660   628273.792  46.595    49.189   17.6   0.0   3.50  
9620  447622.068  1523938.917  40.863    27.765   14.1   0.0   4.80  

[9621 rows x 14 columns]

In [29]:
pd.read_csv('test.csv')

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [37]:
train = pd.read_csv('train.csv')
train.info()
train.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S